language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
    - test/integration
before_install:
  - mkdir ./config
  - openssl aes-256-cbc -K $encrypted_c4bb41b9929c_key -iv $encrypted_c4bb41b9929c_iv -in production.json.enc -out ./config/production.json -d
  - openssl aes-256-cbc -K $encrypted_c4bb41b9929c_key -iv $encrypted_c4bb41b9929c_iv -in test.json.enc -out ./config/test.json -d
services:
  - mongodb
