language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - dev
before_install:
  - openssl aes-256-cbc -K $encrypted_86553c6708a8_key -iv $encrypted_86553c6708a8_iv -in ./config/secrets.tar.enc -out ./config/secrets.tar -d
  - tar xvf ./config/secrets.tar -C ./config
script:
  - yarn workspace client build
  - yarn test
services:
  - mongodb
