language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
    - test/integration
before_install:
  - openssl aes-256-cbc -K $encrypted_6de00bfef5b7_key -iv $encrypted_6de00bfef5b7_iv -in ./config/production.json.enc -out ./config/production.json -d
  - openssl aes-256-cbc -K $encrypted_6de00bfef5b7_key -iv $encrypted_6de00bfef5b7_iv -in ./config/test.json.enc -out ./config/test.json -d
services:
  - mongodb
